name: fibrin
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - opencv
  - pandas
  - ipykernel
  - sqlalchemy
  - scikit-image
  - matplotlib
  - torchvision
  - torchaudio
  - pytorch
  - pytest
