name: fibrin
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - ipykernel
  - sqlalchemy
  - scikit-image
  - matplotlib
  - pytest
  - py-opencv
  - scikit-learn
  - scipy
  - umap-learn
  - pytorch=2.7.1=cuda126_mkl*
  - torchvision
  - torchaudio
